@startuml Diagramme sequence

participant "Utilisateur" as U

participant "ControleurBoutonOpenDirectory" as CBOF

participant "ControleurBoutonOpenFile" as CBSF

participant "FileChooser" as FC

participant "Classe" as C


participant "Modele" as M
activate U 
U -> CBOF : Appuie sur le bouton 
activate CBOF
CBOF -> FC : new()
activate FC
FC --> CBOF : File
deactivate FC
CBOF -> M : setSujet(Classe)
activate M
M -> M : notifierObservateurs()
M --> CBOF
deactivate M
CBOF --> U
deactivate CBOF
alt Ouvrir un fichier
    U -> CBSF : Appuie sur le bouton
    activate CBSF
    CBSF -> FC : new()
    activate FC
    FC --> CBSF : File
    deactivate FC
    CBSF -> C : new(File)
    activate C
    C --> CBSF : Classe
    deactivate C
    CBSF -> M : ajouterClasse(Classe)
    activate M
    M -> M : notifierObservateurs()
    M --> CBSF
    deactivate M
    CBSF --> U
    deactivate U

end
@enduml